### ISSUE TITLE
lokalise_rails:import fails in v4.0.0

### ISSUE THREAD

**Issue by SidorenkoD** [bodrovis/lokalise_rails#10]
Running of `rails lokalise_rails:import` raises
`#<NoMethodError: undefined method 'filter' for #<Array:...>>`

The reason is usage of `Array#filter` [here](https://github.com/bodrovis/lokalise_manager/blob/v2.1.0/lib/lokalise_manager/task_definitions/base.rb#L21). `Array#filter` was [added](https://github.com/ruby/ruby/blob/v2_6_0/NEWS) in Ruby 2.6, while gemspec of `lokalise_manager` v2.1.0 [is meant](https://github.com/bodrovis/lokalise_manager/blob/v2.1.0/lokalise_manager.gemspec#L15) to work on Ruby 2.5.0

**Comment by bodrovis** [comment]
Yeah, unfortunately it seems to be the case. I'm sorry for this! Here's a quick solution:

```ruby
class Array
  def filter(&block)
    self.select(&block)
  end
end
```

This will serve as polyfill for the `filter` method (`select` should be available in 2.5).

**Comment by bodrovis** [comment]
I've published lokalise_manager v2.2.1 which is used by lokalise_rails v4 and fixed that issue https://github.com/bodrovis/lokalise_manager/commit/9fc47fb7c5bcaa002c0ba77e40e60af492d57b5d Just to be on a safe side, you can manually include it into your Gemfile:

```ruby
lokalise_rails, '~> 4'
lokalise_manager, '2.2.1'
```

**Comment by SidorenkoD** [comment]
Now there's a problem with `faraday`:
1. `lokalise_manager` v2.2.1 [requires](https://github.com/bodrovis/lokalise_manager/blob/v2.2.1/lokalise_manager.gemspec#L26) `ruby-lokalise-api` v5.0
2. `ruby-lokalise-api` v5.0 [requires](https://github.com/lokalise/ruby-lokalise-api/blob/v5.0.0/ruby-lokalise-api.gemspec#L26) `faraday` v2.0
3. `faraday` v2.0 [requires](https://github.com/lostisland/faraday/blob/v2.0.0/faraday.gemspec#L16) Ruby 2.6

Please check all your dependecies chain on Ruby 2.5, so I'm not ought to report it again =)

**Comment by bodrovis** [comment]
Weeeell, yeah. Formally, this gem had Ruby 2.5 specified as a supported platform but actually I'm pretty sure it was a mistake from my side as it was never tested with that version, at least starting from v3. Ruby 2.5 was abandoned quite some time ago and I really don't have any plans to backport this gem for Ruby 2.5, to be honest. I'll see what can be done but can't give any promises :(

**Comment by bodrovis** [comment]
Perhaps, the simplest solution is to stay on v3 which is very similar to v4 (the main difference is that it doesn't use multithreading). In this case you should be good as it relies on Faraday 1.
